#!/usr/bin/env bash
# Displays "Best School" 10 times using a while loop but the 9th time display "Hi"

counter=1

while [ $counter -le 10 ]; do
    if [ $counter -eq 9 ]; then
        echo "Hi"
    else
        echo "Best School"
    fi
        ((counter++))
done
